allowBuilds:
  '@prisma/engines': true
  '@tailwindcss/oxide': true
  esbuild: true
  msw: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@mswjs/interceptors@0.45.5'
  - msw@3.0.0
